### ISSUE TITLE
Where to put Survey Date and Time?

### ISSUE THREAD

**Issue by raymrdc** [Bayes-Price/TSAPI#21]
Can the Survey Date and Time be added to the Variables of SurveyMetadataBase? This is for when the survey was taken.

**Comment by tbrandwood** [comment]
Currently, we've not made any explicit provision for this.  
I can see two possible approaches: 

1. We add an "InterviewDate" entry to the UseType enum - allowing a (date) variable to be flagged for this special purpose
2. We add a "Date" property to the Interview Domain class so this data is then, essentially, attached  as interview "metadata"

My preference is for 2) since the Interview Date is more a property of the Interview rather than an explicit survey question.

What do you think?

**Comment by raymrdc** [comment]
yes let's put it in Interview domain. That will be similar to Triple S standard.

**Comment by tbrandwood** [comment]
Hi Ray, 
Just to let you know, "Date" (and "Complete") has been added to the "Interview" domain class.
